#!/bin/sh

# create configure from configure.ac
# create Makefile.in's from Makefile.am's

set -x

mkdir -p config

aclocal && \
  libtoolize --copy --force && \
  autoheader && \
  autoconf && \
  automake -a -c

rm -rf autom4te.cache
