.\" This file is part of gpib-utils.
.\" For details, see http://sourceforge.net/projects/gpib-utils.
.\"
.\" Copyright (C) 2005 Jim Garlick <garlick@speakeasy.net>
.\"
.\" gpib-utils is free software; you can redistribute it and/or modify
.\" it under the terms of the GNU General Public License as published by
.\" the Free Software Foundation; either version 2 of the License, or
.\" (at your option) any later version.
.\"
.\" gpib-utils is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\"
.\" You should have received a copy of the GNU General Public License
.\" along with gpib-utils; if not, write to the Free Software Foundation, 
.\" Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
.TH hptodino 1  2005-11-25 "" "gpib-utils"
.SH NAME
hptodino \- convert HP 1630/1631 state/timing dumps to DECSIM ASCII
.SH SYNOPSIS
.nf
.B hptodino [-c clockspeed] <dumpfile >dinofile
.fi
.SH DESCRIPTION
\fBhptodino\fR is a filter that converts HP 1630/1631 logic analyzer
state/timing dumps to DECSIM ASCII format that can be read by dinotrace.
.SH EXAMPLE
State trace (presumes 1 us clock, and existing state.dino file):
.IP
.nf
hp1630 --save-state >state.dump
hptodino -c 500ns <state.dump >state.tra
dinotrace state.tra
.fi
.PP
Timing trace (presumes 10 ns clock, and existing timing.dino file):
.IP
.nf
hp1630 --save-timing >timing.dump
hptodino -c 10ns <timing.dump >timing.tra
dinotrace state.tra
.fi
.SH "SEE ALSO"
http://www.veripool.com/dinotrace
.PP
hp1630(1)
