.\" This file is part of gpib-utils.
.\" For details, see http://sourceforge.net/projects/gpib-utils.
.\"
.\" Copyright (C) 2005 Jim Garlick <garlick@speakeasy.net>
.\"
.\" gpib-utils is free software; you can redistribute it and/or modify
.\" it under the terms of the GNU General Public License as published by
.\" the Free Software Foundation; either version 2 of the License, or
.\" (at your option) any later version.
.\"
.\" gpib-utils is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\"
.\" You should have received a copy of the GNU General Public License
.\" along with gpib-utils; if not, write to the Free Software Foundation, 
.\" Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
.TH hptopbm 1  2005-04-05 "" "gpib-utils"
.SH NAME
hptopbm \- convert HP-graphics to portable bitmap (PBM) format
.SH SYNOPSIS
.nf
.B hptopbm <hp-graphics-file >pbm-file
.fi
.SH DESCRIPTION
\fBhptobpm\fR is a filter that converts HP-graphics bitmap format
to portable bitmap (PBM) format on standard output.
HP-graphics format is read by older HP ThinkJet printers such as the 
HP 2671G and is produced by older HP instrumentation like HP 1630 logic
analyzer series.
.SH EXAMPLE
To print an HP logic analyzer screen dump on a postscript printer:
.IP
hp1630 --print-screen | hptopbm | pbmtolps -dpi 100 | lpr
.SH "SEE ALSO"
hp1630(1), pbmtolps(1), thinkjettopbm(1), pbm(5)
